// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIzNz_Xa3p6yvcu7umP0TlAqmSLB0JQo',
    appId: '1:318563725550:web:d55a7a132f0a9aaec943ff',
    messagingSenderId: '318563725550',
    projectId: 'wechat-5b85c',
    authDomain: 'wechat-5b85c.firebaseapp.com',
    storageBucket: 'wechat-5b85c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgT2laXG0yrWYkEHJk8oqNsRqPRC3k4MY',
    appId: '1:318563725550:android:c5fa3a8f334af17fc943ff',
    messagingSenderId: '318563725550',
    projectId: 'wechat-5b85c',
    storageBucket: 'wechat-5b85c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYz4S2QjE3c1wFiMOqDoYC6G7v72Np52I',
    appId: '1:318563725550:ios:1c35a17bd3a09f13c943ff',
    messagingSenderId: '318563725550',
    projectId: 'wechat-5b85c',
    storageBucket: 'wechat-5b85c.appspot.com',
    androidClientId: '318563725550-j8on00vodfqtbbilo5b9ni012klhvkk7.apps.googleusercontent.com',
    iosClientId: '318563725550-m7p44j5jetut6ort41q7mne5dgju6g2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYz4S2QjE3c1wFiMOqDoYC6G7v72Np52I',
    appId: '1:318563725550:ios:1c35a17bd3a09f13c943ff',
    messagingSenderId: '318563725550',
    projectId: 'wechat-5b85c',
    storageBucket: 'wechat-5b85c.appspot.com',
    androidClientId: '318563725550-j8on00vodfqtbbilo5b9ni012klhvkk7.apps.googleusercontent.com',
    iosClientId: '318563725550-m7p44j5jetut6ort41q7mne5dgju6g2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChar',
  );
}
